name: Publish Edge
on:
  push:
    branches:
      - develop

jobs:
  publish-edge:
    name: Publish Edge
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.14.1]
    steps:
      - name: Checkout
        uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Test Types
        run: |
          yarn test-types
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6e9b583c9652e99b72b042a3957980fc6166efae
        with:
          spec: cypress/integration/index.spec.js
      - name: Publish Edge
        run: |
          . ./scripts/publish-utils.sh
          setup_git
          COMMIT=${GITHUB_SHA:0:7}
          sed -i "s/  \"version\": \"\([0-9]\+\).\([0-9]\+\).\([0-9]\+\)/&-$GITHUB_RUN_NUMBER-$COMMIT/" package.json
          git commit -a -m "Updating version [skip ci]" --allow-empty
          npm publish --access public --tag edge
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    services:
      nodeos:
        image: eosio/eosjs-ci:develop

        ports:
          - 8888:8888
          - 9876:9876
